#! /bin/csh -f

echo '' > cpu0.acc
echo '' > bus.acc

make dcache_tb.ghw

echo  'verifying'
wc -l cpu0.acc | tr '\012' ' '
echo 'access'
wc -l bus.acc | tr '\012' ' '
echo 'access'

# cat cpu0.acc | \
#   cut -c2-8 > tmp.1

# cat cpu0.acc | \
#   cut -c11-17 > tmp.2

cat cpu0.acc | \
  awk '{print $1, $2, $3}' | \
  grep '1 *$' | \
  awk '{print $1, $2}' | \
  sed -e 's/^.//' > tmp.5
cat tmp.5 | \
  sed -e '$d' > tmp.6

cat  dcache_tb.vhd | \
  grep '^  acc_vect' | \
  cut -c23-40 | \
  sed -e 's/^........../& /' \
      -e 's/^.../& 0/' \
      -e 's/^../& /' \
      -e 's/^./& /' | \
  awk '{if (($1 == 1) || ($1 == 3)) {print ($2 % 2), $4, $5}}' | \
  sed -e '/^0........[159D]/s/^.........../&%/' \
      -e                   's/%../mm/' \
      -e '/^0........[159D]/s/^.............../&%/' \
      -e '/^0........[26AE]/s/^.........../&%/' \
      -e                   's/%..../mmmm/' \
      -e '/^0........[37BF]/s/^.........../&%/' \
      -e                   's/%....../mmmmmm/' | \
  awk '{print $2, $3, $1}'				 >  tmp.1

tail -248						    tmp.1 \
   > tmp.10
cat tmp.10 tmp.10 tmp.10 tmp.10	tmp.10			 >> tmp.1

if (-z cpu0.acc) then
  echo 'veryfy ng (cpu0.acc empty)'
else

  cat tmp.1 | \
    head -`cat cpu0.acc | wc -l` > tmp.2

  cat cpu0.acc | \
    awk '{print $3, $1, $2}' | \
    sed -e '/^0........[159D]/s/^.........../&%/' \
        -e                   's/%../mm/' \
        -e '/^0........[159D]/s/^.............../&%/' \
        -e '/^0........[26AE]/s/^.........../&%/' \
        -e                   's/%..../mmmm/' \
        -e '/^0........[37BF]/s/^.........../&%/' \
        -e                   's/%....../mmmmmm/' | \
    awk '{print $2, $3, $1}' > tmp.4

  diff -w tmp.4   tmp.2 > tmp.3
  if (-z tmp.3) then
    echo 'cpu r/w verify ok'
  else
    echo 'cpu r/w veryfy ng'
  endif
endif

if (-z bus.acc) then
  echo 'veryfy ng (bus.acc empty)'
else
  diff -w tmp.5 bus.acc > tmp.10
  diff -w tmp.6 bus.acc > tmp.11
  if (-z tmp.10) then
    echo 'bus-cpu store verify ok'
  else
    if (-z tmp.11) then
      echo 'bus-cpu store verify ok'
    else
      echo 'bus-cpu store veryfy ng'
    endif
  endif
endif

if (-z bus.acc) then
else
  if(-z snoopo.acc) then
    echo 'verify ng (snoopo.acc empty)'
  else
    cat bus.acc | \
      cut -c1-6 | \
      sed \
        -e 's/1$/0/' -e 's/3$/2/' -e 's/5$/4/' -e 's/7$/6/' \
        -e 's/9$/8/' -e 's/B$/A/' -e 's/D$/C/' -e 's/F$/E/' \
      > tmp.5
    cat tmp.5 | sed -e '$d' > tmp.6
    grep -n '^' snoopo.acc | \
      egrep '2:|4:|6:|8:|0:' | \
      sed    -e 's/^.*://' > tmp.12ev
    set TMP_12EVLINES = `wc tmp.12ev | awk '{print $1}'`
    grep -n '^' snoopo.acc | \
      egrep '1:|3:|5:|7:|9:' | \
      sed    -e 's/^.*://' | \
      sed -n -e '1,'${TMP_12EVLINES}'p' > tmp.12od
    diff tmp.12ev tmp.12od > tmp.13
    diff tmp.5 tmp.12ev    > tmp.10
    diff tmp.6 tmp.12ev    > tmp.11
    if (-z tmp.10) then
      echo 'bus-W snoop-W match ok'
    else
      if (-z tmp.11) then
        echo 'bus-W snoop-W match ok'
      else
        echo 'bus-W snoop-W match ng'
      endif
    endif
    if(-z tmp.13) then 
      echo 'snoop address 2 cycles keep ok'
    else
      echo 'snoop address 2 cycles keep ng'
    endif
  endif
endif

