#! /bin/csh -f

cat dcache_tb.vhd | \
  grep '^  acc_vect.*x.[13]' | \
  sed -e 's/^.*x//' | \
  tr '";' '  '  | \
  sed -e 's/..........$/ &/' \
      -e 's/..................$/ 0&/' \
      -e 's/^.../& /' \
      -e 's/^../& /' | \
  awk ' \
  { \
    if($1 == "1") { print $4, $5, $2, "0"; } \
    else          { print $4, $5, $2, "1"; } \
  }' | \
  sed -e '$d' > tmp.1
